### ISSUE TITLE
Message: Session matching query does not exist.

### ISSUE THREAD

**Issue by rcorzogutierrez** [mburst/django-realtime-tutorial#4]
when I enter text in the console shows me the message "Message: Session matching query does not exist."

**Comment by mburst** [comment]
Sounds like you may not be logged in

**Comment by devBuggs** [comment]
I want to `re-open` this issue.. i also got same issue.. 
When i login to django admin panel, server raise error, error log -->

> 
> 2021-09-24 04:28:32,909: Not Found: /favicon.ico
> 2021-09-24 04:28:32,910: OSError: write error
> 2021-09-24 14:47:46,933: Not Found: /favicon.ico
> 2021-09-24 14:48:35,122: Internal Server Error: /admin/
> Traceback (most recent call last):
>   File "/usr/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
>     response = get_response(request)
>   File "/home/yourcourse/yourcourse/accounts/middlewares.py", line 12, in __call__
>     Session.objects.get(session_key = stored_session_key).delete()
>   File "/usr/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
>     return getattr(self.get_queryset(), name)(*args, **kwargs)
>   File "/usr/lib/python3.8/site-packages/django/db/models/query.py", line 406, in get
>     raise self.model.DoesNotExist(
> django.contrib.sessions.models.Session.DoesNotExist: Session matching query does not exist.

I have created a copy of django session in database and added a OneSessionPerUserMiddleware.. sometimes it works fine but sometimes 🤯..
